// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOdr2VHUrlhd6bqD_AUq6YKDocOTOZPhQ',
    appId: '1:622317379656:web:948dce52713ceaf33e387d',
    messagingSenderId: '622317379656',
    projectId: 'todoapp-7f457',
    authDomain: 'todoapp-7f457.firebaseapp.com',
    storageBucket: 'todoapp-7f457.firebasestorage.app',
    measurementId: 'G-XP8XNFR1SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jEUN5Nr0ENeQCYkGz69VS-Sz7z_UalY',
    appId: '1:622317379656:android:0b837b795d8532353e387d',
    messagingSenderId: '622317379656',
    projectId: 'todoapp-7f457',
    storageBucket: 'todoapp-7f457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkTfaj9meQ7wbIG0Sav-BkD3H8CrwaaA',
    appId: '1:622317379656:ios:f201f82b98e11c0a3e387d',
    messagingSenderId: '622317379656',
    projectId: 'todoapp-7f457',
    storageBucket: 'todoapp-7f457.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkTfaj9meQ7wbIG0Sav-BkD3H8CrwaaA',
    appId: '1:622317379656:ios:f201f82b98e11c0a3e387d',
    messagingSenderId: '622317379656',
    projectId: 'todoapp-7f457',
    storageBucket: 'todoapp-7f457.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOdr2VHUrlhd6bqD_AUq6YKDocOTOZPhQ',
    appId: '1:622317379656:web:1343cf9907dffea93e387d',
    messagingSenderId: '622317379656',
    projectId: 'todoapp-7f457',
    authDomain: 'todoapp-7f457.firebaseapp.com',
    storageBucket: 'todoapp-7f457.firebasestorage.app',
    measurementId: 'G-7MJSVQG5QV',
  );
}
